//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcW3CLOUDwpf.JCW3CLOUDReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JCW3CLOUDPage", Namespace="http://schemas.datacontract.org/2004/07/jcW3CLOUD")]
    [System.SerializableAttribute()]
    public partial class JCW3CLOUDPage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string HTMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string HTML {
            get {
                return this.HTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.HTMLField, value) != true)) {
                    this.HTMLField = value;
                    this.RaisePropertyChanged("HTML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCW3CLOUDReference.IJCW3CLOUD")]
    public interface IJCW3CLOUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCW3CLOUD/renderPage", ReplyAction="http://tempuri.org/IJCW3CLOUD/renderPageResponse")]
        jcW3CLOUDwpf.JCW3CLOUDReference.JCW3CLOUDPage renderPage(string URL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCW3CLOUDChannel : jcW3CLOUDwpf.JCW3CLOUDReference.IJCW3CLOUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCW3CLOUDClient : System.ServiceModel.ClientBase<jcW3CLOUDwpf.JCW3CLOUDReference.IJCW3CLOUD>, jcW3CLOUDwpf.JCW3CLOUDReference.IJCW3CLOUD {
        
        public JCW3CLOUDClient() {
        }
        
        public JCW3CLOUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCW3CLOUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCW3CLOUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCW3CLOUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public jcW3CLOUDwpf.JCW3CLOUDReference.JCW3CLOUDPage renderPage(string URL) {
            return base.Channel.renderPage(URL);
        }
    }
}
